apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook #deploy to this namespace
    server: "https://kubernetes.default.svc" #deploy to this cluster
  project: default
  source: 
    path: argocd-local/argocd-demo-app/guestbook
    repoURL: "https://github.com/MollyH1391/argocd-kind-cluster.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # create the namespace if it is not exist